version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    include: scope
    prefix: "chore(deps):"
    prefix-development: "chore(deps-dev):"
