language: node_js

node_js:
  - "10"

cache: yarn

services:
  - docker

before_install:
  - cd test/docker
  - docker-compose up -d
  - cd ../..

script:
  - pwd
  - yarn
  - sed -i s/this\.muxer\.unpipeFrom\(buffer\)/buffer\.end\(\)/ node_modules/amqplib/lib/connection.js
  - yarn run coverage
