language: node_js
node_js:
- '16'
cache: yarn
services:
- docker
before_install:
- ./test/start-rabbit.sh
script:
- pwd
- yarn
- yarn run lint
- yarn run coveralls
- yarn run build:ts
deploy:
  provider: npm
  email: kristjantammekivi@gmail.com
  skip_cleanup: true
  api_key:
    secure: PUbEUfkfRuAo47W+uwtTMiX64mjwjCe0JI+3BPiKlkuQZ1EJdKpKK4Gv0qPMfIUeOvM860vHJvhyrnQ+ylqGXUkqdbpl4AamrB1EqfG5C6SrL2vbK86aBbiOlpx1kD857HOghlJWS7+4rqrR3krd3NtQ2xUFHWeUA5A0y3EHIPjE0a8T3Pd7ogWzfiNPbEtap7jkKt5TW/J9Nme4cUUhy0PN14qagYKiDRHtl42K6QPya5Kh/gN+IJD0iqM7gOhu8RTnDM4Afscw+dIuPynAFRDHU7Zz7M8tc15SosWmI0bASe3ROkB+TqNqrSxFOjDcksZIxCDQk6qFKWmdpAuUcZ+Oc2OxqvGxfyeIQ6J+4UZoRNoINgLo0DYou8t9+fDGuyg+N5xahzL77CS9Ei6FW4FxR8xu/J6FxomSVJp5RpmPRDshYm1irgsvCk80diS6JUkxOFDNiz8BDmO95gKlC9O71S/ZRlZvauUG0SMCN2FKNhMSg0rYqdd0hyg5mQEb+ywoL/7s7z/eNyg5gjA0zKPiRR9TFY1KL+9DzZWdMfiPR0D9J/TVUMLIH48l8g0fvQYm+xWx1xwniRliqA57MnQ4/61yevK/yYV+0anIW2RqLvu2qbBi9IeN3umvrTubmfzhP4ndY9/bBO24vK5Uzr55CYaEnnmVxQ9zBk/O/qk=
  on:
    tags: true
    branch: master
    repo: KristjanTammekivi/Haredo
