language: node_js
node_js:
- '10'
cache: yarn
services:
- docker
before_install:
- cd test/docker
- docker-compose up -d
- cd ../..
script:
- pwd
- yarn
- yarn run coverage
- yarn run build:ts
deploy:
  provider: npm
  email: kristjantammekivi@gmail.com
  skip_cleanup: true
  api_key:
    secure: KQ2H6xSq7LfGWb55dvHFEnKJx2pVCaYNSvOH8FWwiS7rZhn4nOZRMUakgAL2mvegiey2tpIg8ArIx3K8/KKQw4lqLibM8qtjlmgKpLwyF1XMCFdmjj1kqDZtWZap9FtfR8suYUPm0r9GQgwkbT6ppBcL2x1nR7AeL/dmPspNGAMuFZPt9suTzDFvqTdWUCL5BGO53apiCS5Hgk1VncqeBfwFKT3eoTZfexWSWacT7P0JMCYMnqMHWXv8D9zJmvgU7gNxMaR4OwvPOGngxUmbMFOhNMJaxmp8WM10R8wfZ0/OlSqASJGQiTF3tyDdhUrnkyi+Npl/wSYKqhMtG4Rpr5tvPrGHr6y3C2KtycqcWf5VaPB8Of4RploiQT8zG8ACl/F3iiYElMNbHgyN6U85AtBLf23xkdNyYnUcR2Fw0bGpXMDSudzU0aHQWcTStbnl6O5DLt95SPy97hC63Od4SgC0HrHXKph4Bwo2naiodl8yoLmOsU+vp9pRh+IcK/J15AwmCACWHAHEesslOQrbf51WEbpCRd3+o5KUpxSUir1nmaPGupX+j9sGXSgkN8UIrvSjSmHc8gqsiCG+daVWYONVzTyUPrYga7zNCfxaRjtIsbHwTD99mYibWNYVUdGENhyP0YyJ8ME/dy50CKPYtfaAhN8rGuJugMM3p9tZ9Z0=
  on:
    tags: true
    branch: master
    repo: KristjanTammekivi/Haredo
