language: node_js
node_js:
- '10'
cache: yarn
services:
- docker
before_install:
- cd test/docker
- docker-compose up -d
- cd ../..
script:
- pwd
- yarn
- yarn run lint
- yarn run coveralls
- yarn run build:ts
deploy:
  provider: npm
  email: kristjantammekivi@gmail.com
  skip_cleanup: true
  api_key:
    secure: cf+Fs78sETJanniP64sXx46Ko+cHmDwaxomnw3vn5C3zN9oyufyL+5CSk93aXqAnPw1/VNqBBHwUe2UmDIg1AQMwQszMYVJwBH/xIj1n0/OGwhH+XX6RxD0Z5niPRZLsh+7bFhtWL9MgAVkfvAN7a3CLZ7yVXecn3RfzTTcZIWhUSklhKWi939ZY1scCe/GqYmw7zA1TBZBMQjLRrIGI3Ywuaq6rRlUxIqV8Avp5coba9ZCK1YZ9UNsIKqcV06tmej+HEFHibQScZ8hP2UFJaBAcC5LzuotI9Zt/PuzI9IfV0XaBcXY4np5JW2bXZvPaa1HGD3v1mBxbNK+EEu/hBgJidpbqWLsPcFGsur1nzvCl7jeUCs4B3vjM+sGqvHaXn2UBen+7vBhGqxeJe8oB+JUrvUcHUUmqih5FMX3H7c0xzln/JkPqJ9jh7VmkOzcXg+kXtkBidVP/bxU8oK1XkqTKhHJ0pQVAWk5QpPub1MBckAl+re0IbI+y8L5jyGnCS8zZGy9FPDxprJsN1SrQ1rffjJnPtyQPdKu7rv0vFNyOTae4xkXd82RpMEYuWNkrFXfeGAXH/fy5vY3IVaEBFjWsnIFxvpGxWSA5CYXUr2jH5eB4pnk5ID++m42b+O+Q2VohSVyXUZ9213De4XAAF5pwyOnpytVv1nBRuNdQLXI=
  on:
    tags: true
    branch: master
    repo: KristjanTammekivi/Haredo

