name: Release Haredo

on:
  push:
    tags:
      - "haredo@*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn
      - run: yarn --cwd packages/haredo run lint
      - run: yarn build
      - run: yarn --cwd packages/haredo publish --non-interactive
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
